# Generated by Django 3.1.6 on 2021-05-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopplist', '0010_auto_20210506_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_abrev',
            field=models.CharField(default='~~~~~~!', max_length=15),
            preserve_default=False,
        ),
    ]
