# Generated by Django 3.1.6 on 2021-05-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopplist', '0012_auto_20210506_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='darkmode',
            field=models.BooleanField(default=False),
        ),
    ]
