# Generated by Django 3.1.6 on 2021-05-10 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopplist', '0013_user_darkmode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shoplist',
        ),
    ]
